"""Compile the AI-redrawn sheet into a small, fixed-palette C sprite asset.

This samples the NEW artwork, never the original illustration. Pillow is only
an offline asset compiler; the executable has no image/library dependency.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
source = Image.open(ROOT / 'assets/redrawn-sheet.png').convert('RGB')
# Intentional shared ramp: outline, hair, skin, jacket, navy, metal, eyes, white.
hexes = ['003969','0b101b','220d24','360b2c','4b1036','651e45',
         'ffe3d2','f5c9b8','d8a491','996b60','392728','51362e',
         '6b483b','805a49','101c32','1b2940','2e3c54','475974',
         '677e99','95abc0','3e4c4e','647372','a1b2ac','f4ffff']
palette = [tuple(bytes.fromhex(h)) for h in hexes]
frames = []
for f in range(6):
    w, h = source.width // 3, source.height // 2
    tile = source.crop(((f % 3)*w, (f // 3)*h, (f % 3+1)*w, (f // 3+1)*h))
    tile = tile.resize((80,80), Image.Resampling.NEAREST)
    pixels = []
    for r,g,b in tile.getdata():
        if r > 180 and b > 160 and g < 90:
            pixels.append(0)
        else:
            pixels.append(min(range(1,len(palette)), key=lambda i: sum((a-v)**2 for a,v in zip(palette[i],(r,g,b)))))
    frames.append(pixels)

header = '/* Generated by tools/pack_sprites.py; artwork: see README.md. */\n'
header += '#define SPRITE_SIZE 80\n#define SPRITE_COUNT 6\n'
header += 'static const unsigned char palette[][3] = {\n'
header += ',\n'.join('{%d,%d,%d}' % p for p in palette) + '\n};\n'
header += 'static const unsigned char sprites[6][80*80] = {\n'
header += ',\n'.join('{\n'+',\n'.join(','.join(map(str,f[y*80:(y+1)*80])) for y in range(80))+'\n}' for f in frames)+'\n};\n'
(ROOT/'src/nyan10chan_sprites.h').write_text(header)
print('Packed six distinct 80×80 frames, 23 opaque colors, transparent index 0.')
